name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        default: "status.faforever.com"
      gitRef:
        description: "The git ref to deploy"
        required: true
        default: "refs/heads/main"

jobs:
  deploy_mj:
    name: Deploy
    environment:
      name: ${{ github.event.inputs.environment }}
      url: https://${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.inputs.gitRef }}

      - name: Upload docker-compose.yml
        uses: appleboy/scp-action@8a54b394594637844fcf9ec5cab3eb97ce5dedae
        with:
          host: status.faf.micheljung.ch
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
          fingerprint: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMk4ZffdaFzraPOAAprIqA54KbknZHhIfEtkMPuiqFBC"
          source: "docker-compose.yml,.env.template"
          target: ${{ secrets.TARGET_DIR }}

      - name: Deploy application
        uses: appleboy/ssh-action@1a8b3784eaa665f677fa114edd5683bb6a6bfaa8
        with:
          host: status.faf.micheljung.ch
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
          fingerprint: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMk4ZffdaFzraPOAAprIqA54KbknZHhIfEtkMPuiqFBC"
          script: |
            cd "${{ secrets.TARGET_DIR }}"
            test -f docker-compose.yml && docker-compose stop
            cat << EOF > .env
            DOMAIN_NAME=${{ github.event.inputs.environment }}
            SERVICE_URL=https://${{ github.event.inputs.environment }}
            ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
            ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}
            EOF
            docker-compose up -d
