name: Deploy

on:
  workflow_dispatch:
    inputs:
      targetDir:
        description: "Where on the server to deploy"
        required: true
        default: "/opt/faf-status"
      targetHost:
        description: "The domain name on which the service will be available"
        required: true
        default: "status.faforever.com"
      gitRef:
        description: "The git ref to deploy"
        required: true
        default: "refs/heads/main"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      TARGET_HOST: ${{ github.event.inputs.targetHost }}
      DOMAIN_NAME: ${{ github.event.inputs.targetHost }}
      TARGET_DIR: ${{ github.event.inputs.targetDir }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.inputs.gitRef }}

      - name: Upload docker-compose.yml
        uses: appleboy/scp-action@8a54b394594637844fcf9ec5cab3eb97ce5dedae
        with:
          host: ${{ env.TARGET_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          source: "docker-compose.yml,.env.template"
          target: ${{ env.TARGET_DIR }}

      - name: Deploy application
        uses: appleboy/ssh-action@1a8b3784eaa665f677fa114edd5683bb6a6bfaa8
        with:
          host: ${{ env.TARGET_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          script: |
            cd "${{ env.TARGET_DIR }}"
            test -f docker-compose.yml && docker-compose stop
            cat << EOF > .env
            ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
            ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}
            DOMAIN_NAME=${{ env.DOMAIN_NAME }}
            EOF
            docker-compose up -d
